### ISSUE TITLE
No 1080p 

### ISSUE THREAD

**Issue by AbhishekBiswas521** [tzsk/hoichoi#19]
No 1080p

**Comment by tzsk** [comment]
Hoichoi doesn't have 1080p. You can see their free content from their website you won't find any 1080p streams.

**Comment by AbhishekBiswas521** [comment]
Now they have it check the quality setting.

**Comment by AbhishekBiswas521** [comment]
Newly added movies, web series, trailers have full hd quality.

**Comment by tzsk** [comment]
Can you please mention a single Series or Movie which has 1080p stream in their site?

**Comment by AbhishekBiswas521** [comment]
This is a free episode https://www.hoichoi.tv/films/title/audition
All the web series now supports 1080 p.

**Comment by AbhishekBiswas521** [comment]
![Screenshot (17)_LI](https://user-images.githubusercontent.com/52816169/61170101-4d234780-a582-11e9-8e75-492e7c8062ac.jpg)
