### ISSUE TITLE
last episodes of any series.

### ISSUE THREAD

**Issue by sk0103** [tzsk/hoichoi#3]
asks to login for last episode

**Comment by tzsk** [comment]
@sk0103 Give a reference link to check out.

**Comment by tzsk** [comment]
#### Windows x64 Bit

1. Download the software for here: [Hoichoi Setup](https://www.filehosting.org/file/details/781671/Hoichoi-1.0.0%20Setup.exe)
2. Install it then Open it and search for any **Series** or **Movies**.
3. Stream it online or Download from the download options.

#### Ubuntu x64 Bit

1. Download the software for here: [Hoichoi Setup](https://www.filehosting.org/file/details/781483/hoichoi_1.0.0_amd64.deb)
2. Install it and then Open it and search for any **Series** or **Movies**.
3. Stream it online or Download from the download options.

**Comment by sk0103** [comment]
Thanks

Let's see if it's working..

**Comment by tzsk** [comment]
# 🔥 Android App Released 🔥 

## Download the APK from here: [Hoichoi TV](https://drive.google.com/file/d/1G0bnJCjKZt3IcyEUxQHIEMq9zct0LldX/view?usp=drivesdk)

### Don't forget to report any issues. 🥇
