### ISSUE TITLE
Script not working anymore

### ISSUE THREAD

**Issue by PritimoySarkar** [tzsk/hoichoi#8]
The temper monkey scripts isn't working anymore also

**Comment by sumanb21** [comment]
Script is not working from last few days

**Comment by tzsk** [comment]
Yes. I saw that today. This is happening because they have patched their security hole... I'll have to find a way to hack that again. But you can always use the Android app to watch hoichoi. If you want a desktop solution, I'll have to make tampermonkey work again which can take time...

**Comment by tzsk** [comment]
# Fixed 🔥 

**Please update the script**

**Comment by Faux16** [comment]
The script isnt working anymore

**Comment by tzsk** [comment]
@Faux16  I know, I have a solution but don't have time to implement. Use the Android 2.0 app.
